# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18KeW5qx3xfcetm_C-7T48voooVVJsIOu
"""
# ENTREGABLE 0: "MAGGIE LEVEL"

from requests.models import Response
import requests
import json
import threading
import time
import csv

def pedirFrase():
# Pedimos los datos a la API:
  while True:
    URL = 'https://thesimpsonsquoteapi.glitch.me/quotes'
    response = requests.get(URL)
    datos = response.json()
    quote = datos[0]["quote"]
    character = datos[0]["character"]
    print(f"El personaje {character} ha dicho: {quote}")

    data = [datos[0]["character"], datos[0]["quote"]]

# Generamos un archivo .csv que guarde las frases de todos los personajes:
    with open('Maggie_Level/General/General.csv', 'a') as file:
        writer = csv.writer(file)
        writer.writerow(data)

# Generamos un archivo .csv que guarde las frases de Homer:
    if datos[0]["character"] == 'Homer Simpson':
      with open('Maggie_Level/Homer/Homer.csv', 'a') as file:
        writer = csv.writer(file)
        writer.writerow(data)

# Generamos un archivo .csv que guarde las frases de Lisa:
    elif datos[0]["character"] == 'Lisa Simpson':
      with open('Maggie_Level/Lisa/Lisa.csv', 'a') as file:
        writer = csv.writer(file)
        writer.writerow(data)
    
    time.sleep(30)

pedirFrase()
